### ISSUE TITLE
Legend names not available in errorbar plots.

### ISSUE THREAD

**Issue by leoschwarz** [cphyc/matplotlib-label-lines#10]
Due to the problem mentioned in https://github.com/matplotlib/matplotlib/issues/8458 `get_line()` for the lines in an errorbar plot is always `_nolegend_`. I'm going to check if there is another way to get the label names or what a workaround for this issue would be (other than using the `LabelLine` api directly).

**Comment by cphyc** [comment]
Thanks for reporting the issue!
 If you find a way around it, please feel free to submit a PR

**Comment by leoschwarz** [comment]
I've found something but it's rather ugly:

```python
lines = plt.gca().get_lines()
labels = plt.gca().get_legend_handles_labels()[1]
for i in range(len(lines)):
    lines[i].set_label(labels[i])
labelLines(lines)
```

We can use `get_legend_handles_labels()` to get the labels of an errorbar plot, but we cannot use the handles because they are not handles to line objects so with this we can combine the two. I personally feel this should be included upstream, but hopefully I'll get around to write a PR at least here soon.

**Comment by cphyc** [comment]
Can you confirm this solves your issue?
