### ISSUE TITLE
auto y_offset

### ISSUE THREAD

**Issue by Fkaule** [cphyc/matplotlib-label-lines#106]
Hello,

thank you for this awesome project! I just wanted to ask if there is any easy way you could think of to auto adjust the yoffset if there is already a label at the same position?

Regards
Felix

**Comment by cphyc** [comment]
Unfortunately, I don't see any way of doing it at the moment in a robust way. That would probably require locating the bounding boxes of all already-present labels before adjusting the offset, but I think it's better to use human placement instead.
