### ISSUE TITLE
Example notebook

### ISSUE THREAD

**Issue by MaxGhenis** [cphyc/matplotlib-label-lines#11]
FYI I took the current example code and made this notebook (also with some minor code style edits). I found it helpful to see each type of invocation with the result inline. Feel free to link if you'd like.

https://colab.research.google.com/drive/1MjcJapFblUagFMuwKX7gow8iD_hd15nQ

![image](https://user-images.githubusercontent.com/6076111/55924746-f4799280-5bbf-11e9-9522-307542943389.png)

**Comment by cphyc** [comment]
Thanks that's a good suggestion. I added it to the repo with a link to the binder instance.

**Comment by cphyc** [comment]
Close by a03ac38074dc7853a55d9bb7df48d04471e4f2d3.
