### ISSUE TITLE
Label for a multiple y values for one x value curve

### ISSUE THREAD

**Issue by pgouvenou** [cphyc/matplotlib-label-lines#122]
Hi,

I try to display label on lines whose have several values of y for one x value. But, I can't manage to have the label on the value of y that I want, even I try every possible values of xvals..

I hope that you can help me,
Thanks,

Pierre

**Comment by cphyc** [comment]
Unfortunately, this isn't possible at the moment. This issue is related to #121, so I'm going to close for now!
