### ISSUE TITLE
Add to Matplotlib third party page

### ISSUE THREAD

**Issue by QuLogic** [cphyc/matplotlib-label-lines#128]
Hi! 

Matplotlib has a [page for third-party packages](https://matplotlib.org/mpl-third-party/); it appears that this package is not listed there. I think it would be useful if you added yourself there: https://github.com/matplotlib/mpl-third-party/

**Comment by cphyc** [comment]
This is an excellent idea! I've opened a PR for that https://github.com/matplotlib/mpl-third-party/pull/154.
