### ISSUE TITLE
Outline sometimes have holes that show the line underneath

### ISSUE THREAD

**Issue by engeir** [cphyc/matplotlib-label-lines#130]
When using the the package to label lines with minus signs, I noticed that the minus signs typically had some artifacts to them. The seemed to be wider on a small segment of their length. (See an example below.)

After digging a bit into it I realized that it occurred due to the `outline_width` not being optimal for the text I had on my lines, and I saw that this was discussed and implemented in #32 and #34, from what I understand its using this [matplotlib effect](https://matplotlib.org/3.1.1/tutorials/advanced/patheffects_guide.html#making-an-artist-stand-out).

I guess it is not really a bug, but since I couldn't find it being mentioned in the example in the README or in [the example](https://github.com/cphyc/matplotlib-label-lines/blob/master/example/matplotlib_label_lines.ipynb), I thought it would be good to include somewhere so users are aware that it can happen, and that tweaking the `outline_width` parameter should be sufficient.

A minimal example showing the effect:

```python
import numpy as np
from matplotlib import pyplot as plt

from labellines import labelLines

X = np.linspace(0, 1, 500)
A = [1, 2, 5, 10, 20]

fig, axes = plt.subplots(ncols=2, nrows=1, constrained_layout=True, figsize=(8, 3))

axes = axes.flatten()

# Changing the outline width gives very different results
outline_width = 10

ax = axes[0]
for a in A:
    ax.plot(X, np.arctan(a * X), label=f"$-{a}$")

labelLines(
    ax.get_lines(),
    zorder=2.5,
    outline_width=outline_width,
    outline_color="black",
    backgroundcolor="red",
)

ax = axes[1]
for a in A:
    ax.plot(X, np.arctan(a * X), label=f"$-{a}$")

labelLines(ax.get_lines(), zorder=2.5, outline_width=outline_width)

plt.show()
```
![lines](https://user-images.githubusercontent.com/38856990/231379082-99bf8487-00bc-46aa-b97d-21fd4f8d5510.png)

**Comment by cphyc** [comment]
Hi, this seems to be a matplotlib bug/issue, see https://github.com/matplotlib/matplotlib/issues/25669.

Let's hope a fix can come from upstream! In the meantime, I'd suggest you test exporting as SVG rather than PNG to see if this fixes your issue. You can then convert the SVG to PNG format using e.g. inkscape.

**Comment by engeir** [comment]
Aha! Thanks, SVG works just as expected. And yes, seem like a matplotlib bug, so feel free to close this issue.
