### ISSUE TITLE
[Feature] Ability to show label on the line but hide from the legend

### ISSUE THREAD

**Issue by cancan101** [cphyc/matplotlib-label-lines#16]
Add the ability to show the label on the line itself but hide the label in the plot legend.

**Comment by cancan101** [comment]
Right now I am using the following:
```python
    handles, labels = g.get_legend_handles_labels()
    by_label = OrderedDict(
        ((l, h) for l, h in zip(labels, handles) if not isinstance(h, Line2D))
    )

    labelLines(g.get_lines())

    g.legend(by_label.values(), by_label.keys())
```

**Comment by cphyc** [comment]
That would be a great addition, but I cannot think of a simple way to implement it (for users)? Maybe one solution would be to add an option to destroy the label for each line when calling the `labelLines`, so that it is not included in the legend?

**Comment by cphyc** [comment]
Hi!
Sorry it took me so long to do this. I implemented it in https://github.com/cphyc/matplotlib-label-lines/commit/1efaf6910e3b259fa241a2841b9e1353e4b6b5d6, tell me if that works for you.
This is now illustrated in the example notebook (https://github.com/cphyc/matplotlib-label-lines/blob/master/example/matplotlib_label_lines.ipynb).
Cheers!

**Comment by cphyc** [comment]
I have closed the issue for now, if you feel this didn't solve your issue, please feel free to reopen it (and document how that could be improved).
