### ISSUE TITLE
Issue with axhline

### ISSUE THREAD

**Issue by cancan101** [cphyc/matplotlib-label-lines#17]
labelLine fails with axhline with `x label location is outside data range!` That is because the x value in get_xdata is 0-1 but the text plots in data coords so that either a value of 0-1 needs to be used for x. I hacked a fix:
```python
    if len(xdata) == 2:
        i = 0
        xa = min(xdata)
        xb = max(xdata)
    else:
        for i, (xa, xb) in enumerate(zip(xdata[:-1], xdata[1:])):
            if min(xa, xb) <= x <= max(xa, xb):
                break
        else:
            raise Exception('x label location is outside data range!')
```

**Comment by cphyc** [comment]
Included in #19 .

**Comment by RemDelaporteMathurin** [comment]
I have a similar issue now with `axhline` with this warning : `UserWarning: The value at position 0 in `xvals` is outside the range of its associated line (xmin=0, xmax=1, xval=12.5). Clipping it into the allowed range.`

**Comment by cphyc** [comment]
I guess it's a matter of implementing a similar fix as @cancan101 above. If you could provide a minimal (non-)working example that'd be wonderful!

**Comment by RemDelaporteMathurin** [comment]
Will do ASAP!

**Comment by cphyc** [comment]
Hey! I'm going to close this for inactivity. If you come back with a MWE, feel free to re-open!

**Comment by RemDelaporteMathurin** [comment]
@cphyc sorry for completely forgetting about this.

This reproduces the issue:

```python
import matplotlib.pyplot as plt
from labellines import labelLines

plt.plot([10, 12, 13], [1, 2, 3], label="plot")
plt.axhline(y=2, label="axhline")

labelLines(plt.gca().get_lines())
plt.show()

```

```
C:\Users\remidm\AppData\Roaming\Python\Python311\site-packages\labellines\core.py:204: UserWarning: The value at position 1 in `xvals` is outside the range of its associated line (xmin=0, xmax=1, xval=11.995). Clipping it into the allowed range.
  warnings.warn(
```


And produces:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/40028739/231582700-52f92d2c-2f9f-47a1-bc32-f92da865c938.png">
