### ISSUE TITLE
Odd whitespace around "i"

### ISSUE THREAD

**Issue by kavanase** [cphyc/matplotlib-label-lines#185]
Using `labelLines` to plot the chemical formula labels in our phase diagrams (using [doped](https://doped.readthedocs.io/en/latest/)), I noticed the whitespace around "i" is odd (in Li2S here)

![image](https://github.com/user-attachments/assets/6fa1854d-7136-4309-b09e-6e4c78893349)

another plot:
![image](https://github.com/user-attachments/assets/bcde1a90-bb20-442c-bc47-b84707e97499)

There seems to be some issue with the way it handles the dot in "i", where it ends up leaving a hollow region in the whitespace?

The function call I'm using is `labelLines(lines, xvals=label_positions, align=False, color="black")`

**Comment by kavanase** [comment]
Increasing `outline_width` with `labelLines(lines, xvals=label_positions, align=False, color="black", outline_width=10)` doesn't seem to fix it:
![image](https://github.com/user-attachments/assets/cbfd906e-67e2-4d60-81bb-52d607d7e84f)

**Comment by cphyc** [comment]
Hi, unfortunately, this is a matplotlib-backend-specific issue, see https://github.com/matplotlib/matplotlib/issues/25669. You can try exporting to SVG and *then* convert into png.

**Comment by kavanase** [comment]
Ok thanks for the reply @cphyc!

**Comment by kavanase** [comment]
Just to confirm, I checked and it was also fine for `pdf` output, only `png` seems to be the issue.
