### ISSUE TITLE
Pip installation fails

### ISSUE THREAD

**Issue by a-jacobo** [cphyc/matplotlib-label-lines#2]
Hi! Thanks for making this function into a pip package!
When I try to install it (Python 2.7, in OsX) with pip I get the following error:

` File "/private/var/folders/sp/7r30s3n961985xnzjdkm1p2m0000gn/T/pip-build-QJzWRo/matplotlib-label-lines/setup.py", line 5, in <module>
        with open('Readme.md') as f:
        IOError: [Errno 2] No such file or directory: 'Readme.md'`

**Comment by cphyc** [comment]
Hi, thanks for your feedback. This should now be fixed. If so, please close the issue!

**Comment by a-jacobo** [comment]
Thanks! It is now fixed.
