### ISSUE TITLE
Poor labels placement

### ISSUE THREAD

**Issue by slaweksiluk** [cphyc/matplotlib-label-lines#20]
Hi, thank you for this great tool. It notably increases plots readability. However for bigger data series (16 lines) labels placement is not optimal, is it possible to tune it to get better locations?

```python
from matplotlib import pyplot as plt
from matplotlib import style
from numpy import genfromtxt
import glob, os
import re
from labellines import labelLine, labelLines
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('xvals', metavar='xvals', type=int, nargs='?',
                    help='Number of x values.')
args = parser.parse_args()

CHANNELS = 16
DATA_SAMPLES = int(args.xvals)
print('Plot for X='+str(DATA_SAMPLES))

file = 'results.txt'
data = genfromtxt(file,delimiter=',')
# Sort by channel
data = data[data[:,4].argsort()]
for i in range(0, CHANNELS):
    low = i*DATA_SAMPLES
    high = (i+1)*DATA_SAMPLES
    D = data[low:high,:]
    # Sort by Y
    D = D[D[:,2].argsort()]
    # Sort by X
    D = D[D[:,3].argsort()]
    X = D[0:DATA_SAMPLES,3]
    Y = D[0:DATA_SAMPLES,2]
    # Total bits tested
    B = D[0:DATA_SAMPLES,0]
    for i in range(0,len(Y)):
        # Zero bits transmitted - link not established
        if B[i] == 0:
            Y[i] = 1.0
        # Zero BER - set some value below x axis for better
        # plot readability
        if Y[i] == 0:
            Y[i] = 1e-12
    label = str(int(data[low,4]))
    plt.semilogy(X, Y, '-', label=label, linewidth=0.8)

plt.legend(loc='best')
plt.ylim(1e-12, 1e0)
labelLines(plt.gca().get_lines())
plt.title('PRBS RX BER')
plt.ylabel('BER')
plt.xlabel('X')
plt.grid(True)
plt.savefig('results.svg')
```

![Zrzut ekranu z 2020-02-28 17-11-24](https://user-images.githubusercontent.com/8343719/75564949-61eb1780-5a4d-11ea-8410-8cbac1f8e95c.png)
[results.txt](https://github.com/cphyc/matplotlib-label-lines/files/4267943/results.txt)

**Comment by MaxGhenis** [comment]
I'm also curious about this, and it looks like a recent update may have moved some labels closer to the ends. For example, a few months ago I made this chart with it:
![image](https://user-images.githubusercontent.com/6076111/79075320-f7153900-7ca6-11ea-8a3b-7085969fb25e.png)

and now, after only changing the colors, the first and last series labels obscure the endpoints of the lines:
![image](https://user-images.githubusercontent.com/6076111/79075373-4ce9e100-7ca7-11ea-9dc9-9bcf0c3875c6.png)

Is there a way to move the labels closer to the center of the lines?

**Comment by cphyc** [comment]
Hi both,
It is always possible to use the `xvals` argument to `labelLines` as follows:
```python
from labellines import labelLines
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 100) 
all_y = [a*x for a in np.arange(0, 1, 0.1)] 

for i, y in enumerate(all_y):
    plt.plot(x, y, label=str(i))

lines = plt.gca().get_lines()
labelLines(lines, xvals=np.linspace(2, 8, len(all_y)))
```
![image](https://user-images.githubusercontent.com/5411875/79123953-3620b880-7d93-11ea-91af-1bcdf23b40cb.png)

@MaxGhenis regarding this change, it may also be due to a change in matplotlib's behaviour, but I am unsure. If you're able to precisely pinpoint the matplotlib/matplotlib-label-lines versions I could try to fix it.

**Comment by MaxGhenis** [comment]
Thanks @cphyc! Adding `xvals=(0.1, 0.9)` produced this improvement:
![image](https://user-images.githubusercontent.com/6076111/79262540-59f10680-7e46-11ea-8d68-890da9c2b0c3.png)

If you'd like, this could be changed in the core code by replacing this section:
https://github.com/cphyc/matplotlib-label-lines/blob/87779da2d1437aca0b4715033561eb3c117abcf8/labellines/core.py#L138-L139
with something like:
```
if xvals is None:
    xlims = ax.get_xlim()  # set axis limits as annotation limits, xvals now a tuple
    SHRINK_FACTOR = 0.05  # How far out from the edges to place closest labels.
    xlims_rng = xlims[1] - xlims[0]
    shrinkage = xlims_rng * SHRINK_FACTOR
    xvals = (xlims[0] + shrinkage, xlims[1] - shrinkage)
```

**Comment by jfonseca8** [comment]
![bad](https://user-images.githubusercontent.com/26664687/79924609-d2833480-83fd-11ea-9c42-2fcaabb6fff2.png)

Hey, guys :) I was able to get desired results with a similar issue.

My issue was that the whitespace behind the label interfered with other lines. I used the following code to alternate the z values of each line to make sure that the data doesn't interfere!

`z = 1
for j in range(5):
        plt.plot(x, y, zorder=testing, label=str(j)
        z = z - 0.1

z = 1
lines = plt.gca().get_lines()
#You'll probably need to play with the x values for perfect fit
x = 5
for j in range(5):
    labelLines([lines[j]], zorder=z, xvals=(x, x + 6), fontsize=8, align=False)
    z = z - 0.1
    x = x + 8` 

![speedup](https://user-images.githubusercontent.com/26664687/79924449-73252480-83fd-11ea-97e4-5667eed2403f.png)

**Comment by cphyc** [comment]
@MaxGhenis this would be a nice addition (with a parameter to control the shrink factor). Would you mind submitting a PR?

**Comment by cphyc** [comment]
@jfonseca8 you may also be interested in using the function `labelLine` (without s) which does the internal job of labeling individual lines.
