### ISSUE TITLE
transparent label background ?

### ISSUE THREAD

**Issue by RemiTheWarrior** [cphyc/matplotlib-label-lines#21]
Is there a way to avoid having white rectangle like this ?

![image](https://user-images.githubusercontent.com/40028739/82424998-38f38500-9a86-11ea-8b49-5dad1518b40e.png)

MWE:

```python
import matplotlib.pyplot as plt
from labellines import labelLine, labelLines

plt.plot([1, 2, 3], label="label")
labelLines(plt.gca().get_lines(), zorder=2.5)
plt.minorticks_on()
plt.grid(which='minor', alpha=0.3)
plt.grid(which='major', alpha=0.7)
plt.show()
```

**Comment by cphyc** [comment]
Hi,

Yes there is, you have to set the background color of the small patch behind the label to, e.g. transparent. This can be achieved using

```python
import matplotlib.pyplot as plt
from labellines import labelLine, labelLines

plt.plot([1, 2, 3], label="label")
labelLines(plt.gca().get_lines(), zorder=2.5, backgroundcolor='none')
plt.minorticks_on()
plt.grid(which='minor', alpha=0.3)
plt.grid(which='major', alpha=0.7)
plt.show()
```
![image](https://user-images.githubusercontent.com/5411875/82425496-7ce28c00-9a7e-11ea-9a68-2932e4cac9b5.png)

The reason there is a white box around the label is to be able to distinguish it from the line behind. You could therefore try to use something like
```python
labelLines(plt.gca().get_lines(), bbox={'pad': -3, 'color': 'white'})
```
to get
![image](https://user-images.githubusercontent.com/5411875/82426368-aa7c0500-9a7f-11ea-8a06-43ac3a109203.png)

**Comment by RemiTheWarrior** [comment]
Cheers !
