### ISSUE TITLE
Adding option to offset y location

### ISSUE THREAD

**Issue by andreamoro-git** [cphyc/matplotlib-label-lines#27]
Sometimes I don't want the label to cover the line. I have added an option to offset the location of labels by a given amount. I wrote a patch and submitted it as a git pull request.

**Comment by cphyc** [comment]
Closed by #26, thanks for the PR!

**Comment by andreamoro-git** [comment]
Can I suggest changing the following in the example code of the fourth chart  to advertise the possibility (subplot 324 in the readme)

labelLine(l1, 0.6, label=r'$Re=${}'.format(l1.get_label()), ha='left',
          align=False, yoffset=.005, va='bottom', bbox={'alpha': 0})

**Comment by andreamoro-git** [comment]
Another good possibility is the yellow line in 326

**Comment by cphyc** [comment]
Done!
