### ISSUE TITLE
Labels not working

### ISSUE THREAD

**Issue by NovaProtocol** [cphyc/matplotlib-label-lines#58]
anyways, 

```py
import matplotlib.pyplot as plt
import numpy as np

from labellines import labelLine, labelLines

xAxis = "x"
yAxis = "y"
title = {"x": "x_axis_title", "y": "y_axis_title"}

plt.title("%s-%s Diagram" % (yAxis, xAxis))
plt.xlabel(title[xAxis])
plt.ylabel(title[yAxis])
plt.grid()

import random

line = []
list_x = [1,2,3,4,5,6,7]

for t in range(len(list_x)):
    x = [x+random.randint(0,10) for x in range(10)]
    y = [y-random.randint(0,10) for y in range(10)]
##    x = [x+t for x in range(10)]
##    y = [y+t for y in range(10)]
    line.extend(plt.plot(x, y, 'g', lw=0.5, label = 'a'))
labelLines(line, zorder=2.5)
plt.show()

```

This doesn't work with the traceback
```
Traceback (most recent call last):
  File "D:\Users\*****\Desktop\test.py", line 132, in <module>
    labelLines(line, zorder=2.5)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\labellines\core.py", line 242, in labelLines
    labelLine(
  File "C:\Users\*****\AppData\Local\Programs\Python\Python39\lib\site-packages\labellines\core.py", line 87, in labelLine
    raise Exception("x label location is outside data range!")
Exception: x label location is outside data range!
```

If I put it inside a while loop and keep trying the code, it eventually works so not sure why it's raising that error. I'm kinda sure I did nothing wrong.

The commented part in the code works but changing it to the uncommented part makes it raise the error.
![image](https://user-images.githubusercontent.com/35219142/132266573-1178dfab-fa39-4d4f-b918-3454c20a2027.png)
This is the expected result if you need it

**Comment by NovaProtocol** [comment]
Oops i accidentally pressed enter lmao

anyways, 

```
import matplotlib.pyplot as plt
import numpy as np

from labellines import labelLine, labelLines

xAxis = "x"
yAxis = "y"
title = {"x": "x_axis_title", "y": "y_axis_title"}

plt.title("%s-%s Diagram" % (yAxis, xAxis))
plt.xlabel(title[xAxis])
plt.ylabel(title[yAxis])
plt.grid()

import random

line = []
list_x = [1,2,3,4,5,6,7]

for t in range(len(list_x)):
    x = [x+random.randint(0,10) for x in range(10)]
    y = [y-random.randint(0,10) for y in range(10)]
##    x = [x+t for x in range(10)]
##    y = [y+t for y in range(10)]
    line.extend(plt.plot(x, y, 'g', lw=0.5, label = 'a'))
labelLines(line, zorder=2.5)
plt.show()

```

This doesn't work with the traceback
Exception: x label location is outside data range!

**Comment by cphyc** [comment]
The issue is that `labelLines` automatically generates x locations to put the label on using the plot limit. This isn't particularly clever as some lines may be much shorter in the `x` direction, and will thus trigger an `Exception`.

A quick workaround is to manually provide the `xvals` where the labels will end up. I am thinking about a more robust solution though, stay tuned!

**Comment by cphyc** [comment]
Hi @NovaProtocol,

I have developed a solution to your problem (see #59). Could you try it out and confirm (or not) it solves your issue?
