### ISSUE TITLE
Labels in the middle of each line

### ISSUE THREAD

**Issue by christoschronopoulos** [cphyc/matplotlib-label-lines#62]
Dear cphyc,

Thank you for the amazing work! I am using the labelling functions but I am wondering if there is a way to keep all the labels to the middle of the lines. It doesn't matter if they might overlap.

This is a screenshot of a plot where I would like the labels to be in the middle.
![image](https://user-images.githubusercontent.com/12989098/134666107-5f5def2f-cc5e-43bc-967e-2811de39df41.png)

Really hope that this is an easy fix that I am missing! Thanks again!

**Comment by cphyc** [comment]
Hi @christoschronopoulos , thanks for the positive feedback, always appreciated!

Regarding your issue, I am unsure I exactly understand what it is you are trying to achieve, but you can always manually provide  the x location of your labels using the `xvals` parameters in the call to `labelLines`, see example below.

```python
from labellines import labelLines
import matplotlib.pyplot as plt
import numpy as np

xx = np.linspace(0, 2*np.pi, 100)

X = (xx, xx)
Y = (np.cos(xx), np.sin(xx))
Xlabels = (np.pi, np.pi)

lines = []
for i, (x, y) in enumerate(zip(X, Y)):
    lines.extend(plt.plot(x, y, label=f"{i=}"))

labelLines(lines, xvals=Xlabels)
```
With xvals:
![Figure_1](https://user-images.githubusercontent.com/5411875/134667460-28b09c70-48df-49fe-ac29-07394fddb11f.png)

Without
![Figure_2](https://user-images.githubusercontent.com/5411875/134667531-91ddf3a0-2eaa-4bad-b6ff-5b6c01775c62.png)
 xvals:

**Comment by cphyc** [comment]
Closing this for now as the issue seems to be stalled. @christoschronopoulos feel free to reopen if the problem persists.
