### ISSUE TITLE
xvals changing?

### ISSUE THREAD

**Issue by AbyFlores** [cphyc/matplotlib-label-lines#68]
Hi! I was wondering what was the input for xvals? I would like the labels to at the end of each plot. 

There are 4 lines being plotted: 3 subjects and the average. My code gets the last value for each subject's line and saves it to x_val_label. I have a print of x_val_label before it goes into labeLines and a print afterwards. I'm not sure why the values are changing?

        plt.figure()
        x_val_label = [] #for labeLines, the position of the label name will be at last point of the line
        for pm in pickled_mice:
            x_values = np.arange(1,len(pickled_dict_mouse_data[pm])+1)
            x_val_label.append(len(pickled_dict_mouse_data[pm])+1) 
            plt.plot(x_values,pickled_dict_mouse_data[pm].iloc[0::,1],color,alpha =0.3,label =pm) #ITI is 1 here
        x_valuesO = np.arange(1,len(overview_df_mouse_data['ITI_avg'])+1)
        x_namesO = overview_df_mouse_data['ITI_avg'].index.tolist()
        plt.plot(x_valuesO,overview_df_mouse_data.iloc[0::,0],color) #ITI_avg is 0 here
        plt.title(pickleGroup + " n" + str(len(pickled_mice)) + ", " + "Additional ITI above 2")
        x_valuesFINAL = x_valuesO
        x_namesFINAL = x_namesO 
        print(x_val_label)
        labelLines(plt.gca().get_lines(), align=False, zorder = 2.5, xvals=x_val_label) 
        print(x_val_label)
>>[18, 14, 14]
[15.4, 11.8, 11.8] 
  
![labelLines_xvals](https://user-images.githubusercontent.com/63807560/141217902-56fb07dd-5311-424d-9150-fe3e06a18ab9.png)

**Comment by cphyc** [comment]
Hi @AbyFlores and thanks for the report.

This is indeed a bug, should be fixed by #69 . Can you confirm?

**Comment by AbyFlores** [comment]
Just wanted to acknowledge that @cphyc went above and beyond in helping me with this bug (as I'm new python I didn't know how to even implement the changes in #69). #69 resolves my x_vals issue.
