### ISSUE TITLE
Throws error for reversed or unsorted lines

### ISSUE THREAD

**Issue by annesteenbeek** [cphyc/matplotlib-label-lines#7]
https://github.com/cphyc/matplotlib-label-lines/blob/81daa2d2e0af1b620bd76cb8257beb1749b34549/labellines/core.py#L31

When I try to label a line on a certain x position e.g. ```labelline(line[1], 0.2, label="test")``` a outside of data range error is thrown.
This is because my data runs from 1.0 to -1.0. This is easily solved by flipping the data in my case.
However this method assumes all data has the highest number on the end and lowest number at the beginning of the array which is not always the case.
This would be solved by using ```np.amin(), np.amax()```

**Comment by cphyc** [comment]
Hi @annesteenbeek,
Thanks for the feedback. This should be fixed by commit 2c75b72a89b704e6145af45c9e2e9e059d781b3a. Could you confirm it is now working?
