### ISSUE TITLE
Dependency issues?

### ISSUE THREAD

**Issue by sblanky** [cphyc/matplotlib-label-lines#83]
When I attempt to import this module

`from labellines import labelLines`

I get the following error

```
File "/home/scott/.local/lib/python3.8/site-packages/labellines/core.py", line 8, in <module>
    from more_itertools import always_iterable
ModuleNotFoundError: No module named 'more_itertools'
```

So I attempt to install `more_itertools` with pip, but it is already installed on my system.

Does this exist for anyone else in the latest release?

**Comment by cphyc** [comment]
This looks like an issue related with the management of pip-installed dependencies. What does the following two commands tell you?
```which pip
which python
```

**Comment by sblanky** [comment]
Sorry for the late reply,

`$ which pip`
`~/.local/bin/pip`

`$ which python`
`~/anaconda3/envs/pyPUC/bin/python`

I think you're right. Basically I'm using an older version of python in my current venv due to some dependency issues on another package. I'm able to use labellines fine when I use the code as a module within my package.
