### ISSUE TITLE
On slope alignments

### ISSUE THREAD

**Issue by ClementPinard** [cphyc/matplotlib-label-lines#9]
Hello, thanks for your repo, which made my life easier and my graph prettier :)

I encountered two problems with alignment with respect to line slope :
 - It does not work for vertical lines. The failing line is [here](https://github.com/cphyc/matplotlib-label-lines/blob/master/labellines/core.py#L46), so maybe we should add a test case when x does not change ?
 - text orientation is very noisy with noisy line, especially with high x-resolution, you could end up with inperceptible noise, but very noisy slope when not filtered, this is the case for my own experiences. Would it be a good idea to figure out x span of the label, and then compute slope with a slope based on the x-span boundaries ? Some borderline would probably be to test however

I encountered another problem that is related to the first point where we compute y based on x : when line is not valid for every x value (with vertical line for example, bust also more simply with lines with shorter lines than the longest). You check that x is within line range ([here](https://github.com/cphyc/matplotlib-label-lines/blob/master/labellines/core.py#L36)), but it conflict with the way you create x values implicitely as linspace from the whole ax range [here](https://github.com/cphyc/matplotlib-label-lines/blob/master/labellines/core.py#L122)
I don't mind doing this simple x repartition, otherwise it would be very complicated to deal with all kinds of line supports, but maybe we can find the nearest x instead of erroring when not in range ?

**Comment by cphyc** [comment]
Hi,
Thanks for the valuable feedback. There is definitely two issues here: 
- division-by-zero error when for vertical line. It is easily fixed by catching the special case where `dx=0`,
- some improvements possible for noisy lines.

Unfortunately I won't have much time to do it myself, but I'm totally fine to accept PR(s) that would fix these issues!

**Comment by cphyc** [comment]
Hi @ClementPinard ,

I think the vertical case should be fixed now. Regarding the issue with noisy line, I think the easiest solution is to allow the user to override the rotation of the ticks so that they can manually set them. What do you think about this?

**Comment by cphyc** [comment]
Closing this for now, as the vertical alignment has been fixed (see https://github.com/cphyc/matplotlib-label-lines/blob/74eaa682aee9766b6e1bc063bf873e784721323f/labellines/core.py#L78).

Regarding the support for noisy line, that can be implemented if there is request for it (or better a PR!).
